### ISSUE TITLE
2.0.2 has better translation

### ISSUE THREAD

**Issue by HazemKhaled** [Magento2Translations/language_ar_sa#1]
It'll be great if you export 2.0.2 since it's has 34% completed

https://crowdin.com/project/magento-2/ar

**Comment by MrGekko** [comment]
Oh yeah I see! I did not know that there was a version difference. I have only used Head. Is it possible to copy the progress from 2.0.2 to the head as i think that will end up in the https://crowdin.com/project/magento-2 project zip. I don't even know how to download the files for 2.0.2 alone..?

**Comment by MrGekko** [comment]
I have requested [Magento](https://crowdin.com/profile/MagentoTranslations) for a propject key with which i can download the different branches like: https://crowdin.com/page/api/download
If that is the case I could create different branches here for all the crowdin branches.

**Comment by HazemKhaled** [comment]
You can use this url
http://107.170.242.99/download.php

**Comment by MrGekko** [comment]
Cool thanks, I asked the creator how he got the different branches! Maybe he can help me. The server is pretty slow though and I would not like to hinge this project on such a potentially slow resource.

Lets hope the creator is willing to help.

**Comment by HazemKhaled** [comment]
That you have to create new branch in this repo in download the csv file directly from this ip, i' sure you also automate it

**Comment by HazemKhaled** [comment]
I just finished code to compare 2.0.2 with Head, i got 10k word translated in 2.0.2 with same key in Head, so i'm preparing XLIFF file for bulk update

**Comment by MrGekko** [comment]
Hi, I have updated my compiler script to use the different http://107.170.242.99/download.php resources. And I have made it use three different Magento2 versions to determain what strings should be translated. All the versions are on different branches. And the master uses the latest Magento 2 and tries to combine all the crowdin branches. But this does not seem to result in something different than the Head branch. Ive added a progress bar and some stats to the readme to see what the different branches entail.

**Comment by HazemKhaled** [comment]
Good work,

1. What is the trigger to update and commit update?
2. I just translated new 200 words in HEAD, can you update it again, please :)

**Comment by MrGekko** [comment]
I have a shell script for updating the languages. The flow goes like this:

- Download/update latest magento's (for all branches)
- Export strings from magento (php magento i18n:collect-phrases --output="***" --magento
- Run custom php commandline compiler (which I will share)
- Commit the translation changes ( not a good practice, but for this usecase-lots of language updates- it works well)

The "compiler" has this flow:
- Download all or some translations from:  http://107.170.242.99/
- Create a new translation file from the translations with the magento strings as a guideline.
- Add common package files (composer, README, language.xml and registration) filled with variables from the translations.

I tried adding this to a cronjob, but for some reason the shellscript does not run on that interval. This is a minor todo. For now I will trigger the script manually..

**Comment by HazemKhaled** [comment]
I think better to write travis script to save your server resources and automate it

travis-ci.org

**Comment by MrGekko** [comment]
When I have time, i'll look into it ;)

**Comment by MrGekko** [comment]
How would you suggest this flow would work? How is the travis build process triggered?With a [cronjob (requires travis support)](https://docs.travis-ci.com/user/cron-jobs/) ?

**Comment by HazemKhaled** [comment]
travis is regular Linux machine, just write you ssh script to do the whole thing, install LAMP stack then Magento, install the language, run export language file, and finally commit your code

as regular as any shell script, you can re-use your current shell script
