### ISSUE TITLE
ar_SA.csv last update from 2 days

### ISSUE THREAD

**Issue by HazemKhaled** [Magento2Translations/language_ar_sa#2]
Last update on this file from 2 days
https://github.com/Magento2Translations/language_ar_sa/blob/master/ar_SA.csv

While 256 new translated after this time
https://crowdin.com/project/magento-2/ar/activity

**Comment by MrGekko** [comment]
I think this is a old issue. Please realize that I still need to implement the travis scripts.

**Comment by HazemKhaled** [comment]
Yes, updated correctly now, Thanks

**Comment by HazemKhaled** [comment]
No updates from a long time, i tried also to compile myself but look outdated
