### ISSUE TITLE
currency not showing

### ISSUE THREAD

**Issue by riadlynx** [Magento2Translations/language_ar_sa#3]
Hi,
When i use this local currency symbole does not appear, can you please fix it? 
thanks

**Comment by HazemKhaled** [comment]
More details @riadlynx, this repo only package translations from crowdin.com, so better to open this link, search you missing or wrong work and fix it.
https://crowdin.com/translate/magento-2/1374/enus-ar

within days you will find update there in this package

**Comment by MrGekko** [comment]
I am not sure what the problem is. Is it the translation of the symbol in the csv or something in Magento blocking your curency symbol. When you disabled/removed this module does the currency symbole show up?

**Comment by riadlynx** [comment]
yes when i use another language it works

**Comment by MrGekko** [comment]
Could you try this when the package is activated? https://www.youtube.com/watch?v=NjBuRbNydX8

**Comment by riadlynx** [comment]
unfortunately still not working

**Comment by MrGekko** [comment]
Have you found a sollution to this problem? I am not sure what to do about it, so i am closing this issue.
